const ACTIONS = {
    REQUEST_PENDING_WITH_LOADER: "REQUEST_PENDING_WITH_LOADER",
    REQUEST_SUCCESSFUL: "REQUEST_SUCCESSFUL",
    REQUEST_FAILED: "REQUEST_FAILED",
    INIT_REDUCER: ""
};

export default ACTIONS;